//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTIVIDAD4.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LenguajeProgrmacionEntities : DbContext
    {
        public LenguajeProgrmacionEntities()
            : base("name=LenguajeProgrmacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<ClIENTES> ClIENTES { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<DetallesCompras> DetallesCompras { get; set; }
        public virtual DbSet<DetallesFactura> DetallesFactura { get; set; }
        public virtual DbSet<FACTURAS> FACTURAS { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Productos_TEMP> Productos_TEMP { get; set; }
        public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }
    }
}
